[
    {
        "nombre_sucursal": "Sucursal Cancún",
        "calle": "Monte Libano MZ54",
        "num_ext": "L54",
        "num_int": "B7,B8,B9,B10",
        "codigo_postal": "77560",
        "colonia": "ALFREDO V. BONFIL",
        "estado": "Quintana Roo",
        "ciudad": "Cancun",
        "pais": "México",
        "telefono": "(99)8415-0807"
    },
    {
        "nombre_sucursal": "Sucursal Cd. Juarez",
        "calle": "Faraday",
        "num_ext": "8750",
        "num_int": "2",
        "codigo_postal": "32470",
        "colonia": "Parque Industrial Antonio J Bermudez",
        "estado": "Chihuahua",
        "ciudad": "Juarez",
        "pais": "México",
        "telefono": "(656)625-9221",
        "codigo": "cd_juarez"
    },
    {
        "nombre_sucursal": "Matriz Chihuahua",
        "calle": "Ave. 20 de Noviembre",
        "num_ext": "805",
        "num_int": "",
        "codigo_postal": "31000",
        "colonia": "Centro",
        "estado": "Chihuahua",
        "ciudad": "Chihuahua",
        "pais": "México",
        "telefono": "(614)415-2525",
        "codigo": "chihuahua"
    },
    {
        "nombre_sucursal": "Chihuahua Norte",
        "calle": "Luis G. Urbina",
        "num_ext": "161",
        "num_int": "",
        "codigo_postal": "31136",
        "colonia": "Complejo Industrial Chihuahua",
        "estado": "Chihuahua",
        "ciudad": "Chihuahua",
        "pais": "México",
        "telefono": "6144152525",
        "codigo": "chihuahua_cedi"
    },
    {
        "nombre_sucursal": "Sucursal Culiacan",
        "calle": "BLVD. FUERZA AEREA MEXICANA",
        "num_ext": "4995",
        "num_int": "10,11,17 Y 18",
        "codigo_postal": "80130",
        "colonia": "BACHIGUALATO",
        "estado": "Sinaloa",
        "ciudad": "CULIACAN ROSALES",
        "pais": "Mexico",
        "telefono": "(668)817-3406",
        "codigo": "culiacan"
    },
    {
        "nombre_sucursal": "Sucursal Guadalajara",
        "calle": "Francisco de Orellana",
        "num_ext": "2412",
        "num_int": "",
        "codigo_postal": "44940",
        "colonia": "Zona Industrial",
        "estado": "Jalisco",
        "ciudad": "Guadalajara",
        "pais": "México",
        "telefono": "(33)3671-0500",
        "codigo": "guadalajara"
    },
    {
        "nombre_sucursal": "Sucursal Hermosillo",
        "calle": "Blvd. Jesus Garcia Morales",
        "num_ext": "52",
        "num_int": "B",
        "codigo_postal": "83210",
        "colonia": "El llano",
        "estado": "Sonora",
        "ciudad": "Hermosillo",
        "pais": "Mexico",
        "telefono": "6144152525",
        "codigo": "hermosillo"
    },
    {
        "nombre_sucursal": "Sucursal Leon",
        "calle": "De la luz",
        "num_ext": "3307",
        "num_int": "7B",
        "codigo_postal": "37280",
        "colonia": "San Pedro de los Hernandez",
        "estado": "Guanajuato",
        "ciudad": "Leon",
        "pais": "Mexico",
        "telefono": "4777966423",
        "codigo": "leon"
    },
    {
        "nombre_sucursal": "Sucursal Los Mochis",
        "calle": "Miguel Hidalgo Oriente esquina con 20 de Noviembre",
        "num_ext": "611",
        "num_int": "",
        "codigo_postal": "81200",
        "colonia": "Centro",
        "estado": "Sinaloa",
        "ciudad": "Los Mochis",
        "pais": "México",
        "telefono": "(668)817-3406",
        "codigo": "mochis"
    },
    {
        "nombre_sucursal": "Sucursal Mérida",
        "calle": "20J",
        "num_ext": "139",
        "num_int": "",
        "codigo_postal": "97139",
        "colonia": "Jardines del Norte",
        "estado": "Yucat&aacute;n",
        "ciudad": "Mérida",
        "pais": "México",
        "telefono": "(999) 188-1291",
        "codigo": "merida"
    },
    {
        "nombre_sucursal": "Sucursal México Norte",
        "calle": "Lauro Villar",
        "num_ext": "120",
        "num_int": "",
        "codigo_postal": "02440",
        "colonia": "Providencia",
        "estado": "Ciudad de M&eacute;xico",
        "ciudad": "Delegación Azcapotzalco",
        "pais": "México",
        "telefono": "(55)5541-4999",
        "codigo": "mexico"
    },
    {
        "nombre_sucursal": "Sucursal México Sureste",
        "calle": "SUBASTA Y PRODUCTORES MANZANA 4",
        "num_ext": "Lotes C,D,E",
        "num_int": "Ejido del Moral",
        "codigo_postal": "09040",
        "colonia": "Delegacion Iztapalapa",
        "estado": "Ciudad de M&eacute;xico",
        "ciudad": "IZTAPALAPA",
        "pais": "México",
        "telefono": "(55) 5640-2330",
        "codigo": "mexico_sur"
    },
    {
        "nombre_sucursal": "Sucursal Monterrey",
        "calle": "Av. Sendero Divisorio",
        "num_ext": "510",
        "num_int": "D",
        "codigo_postal": "66422",
        "colonia": "Balcones de Anahuac",
        "estado": "Nuevo Le&oacute;n",
        "ciudad": "San Nicolas de los Garza",
        "pais": "México",
        "telefono": "(81)8331-0333",
        "codigo": "monterrey"
    },
    {
        "nombre_sucursal": "Sucursal Monterrey Centro",
        "calle": "Iztaccihuatl",
        "num_ext": "505 Norte",
        "num_int": "0",
        "codigo_postal": "64430",
        "colonia": "Urdiales",
        "estado": "Nuevo Le&oacute;n",
        "ciudad": "Monterrey",
        "pais": "Mexico",
        "telefono": "6144152525"
    },
    {
        "nombre_sucursal": "Sucursal Puebla",
        "calle": "28 NORTE",
        "num_ext": "215",
        "num_int": "",
        "codigo_postal": "72373",
        "colonia": "RESURGIMIENTO CD. NORTE",
        "estado": "Puebla",
        "ciudad": "Puebla",
        "pais": "México",
        "telefono": "(222) 946-2319",
        "codigo": "puebla"
    },
    {
        "nombre_sucursal": "Sucursal Queretaro",
        "calle": "Carretera Al Campo Militar km.25",
        "num_ext": "Nave",
        "num_int": "B-3",
        "codigo_postal": "76135",
        "colonia": "San Antonio de la Punta",
        "estado": "Quer&eacute;taro",
        "ciudad": "Queretaro",
        "pais": "México",
        "telefono": "4421926950",
        "codigo": "queretaro"
    },
    {
        "nombre_sucursal": "Sucursal Queretaro II",
        "calle": "Carretera Al Campo Militar km.25",
        "num_ext": "Nave",
        "num_int": "A-3",
        "codigo_postal": "76135",
        "colonia": "San Antonio de la Punta",
        "estado": "Quer&eacute;taro",
        "ciudad": "Queretaro",
        "pais": "México",
        "telefono": "4421926950"
    },
    {
        "nombre_sucursal": "Sucursal San Luis Potosi",
        "calle": "Av. Industrias",
        "num_ext": "2285",
        "num_int": "",
        "codigo_postal": "78399",
        "colonia": "Industrias",
        "estado": "San Luis Potosi",
        "ciudad": "San Luis Potosi",
        "pais": "Mexico",
        "telefono": "4444751400",
        "codigo": "san_luis_potosi"
    },
    {
        "nombre_sucursal": "Sucursal Tepotzotlan",
        "calle": "06 DE ENERO",
        "num_ext": "04",
        "num_int": "NAVE 16",
        "codigo_postal": "54616",
        "colonia": "LAS ANIMAS",
        "estado": "Estado de M&eacute;xico",
        "ciudad": "TEPOTZOTLAN",
        "pais": "MEXICO",
        "telefono": "6144152525",
        "codigo": "tepotzotlan"
    },
    {
        "nombre_sucursal": "Sucursal Tijuana",
        "calle": "BLVD. FEDERICO BENITEZ",
        "num_ext": "8800",
        "num_int": "2",
        "codigo_postal": "22450",
        "colonia": "Las Brisas, Deleg. La Mesa",
        "estado": "Baja California",
        "ciudad": "TIJUANA",
        "pais": "México",
        "telefono": "(664) 104-5404",
        "codigo": "tijuana"
    },
    {
        "nombre_sucursal": "Sucursal Toluca",
        "calle": "ALFRED NOBEL",
        "num_ext": "378",
        "num_int": "",
        "codigo_postal": "50160",
        "colonia": "DELEGACION SANTA ANA TLAPALTITLAN",
        "estado": "Estado de M&eacute;xico",
        "ciudad": "TOLUCA DE LERDO",
        "pais": "MEXICO",
        "telefono": "6144152525",
        "codigo": "toluca"
    },
    {
        "nombre_sucursal": "Sucursal Torreon",
        "calle": "Carretera Union La Partida",
        "num_ext": "1823",
        "num_int": "4",
        "codigo_postal": "27410",
        "colonia": "Ana",
        "estado": "Coahuila",
        "ciudad": "Torreon",
        "pais": "Mexico",
        "telefono": "6144152525",
        "codigo": "torreon"
    },
    {
        "nombre_sucursal": "Sucursal Veracruz",
        "calle": "CARR. VERACRUZ-MEDELLIN KILOMETRO 1",
        "num_ext": "S/N",
        "num_int": "BODEGA 2",
        "codigo_postal": "91948",
        "colonia": "EL JOBO",
        "estado": "Veracruz",
        "ciudad": "VERACRUZ",
        "pais": "MEXICO",
        "telefono": "229-621-48-50",
        "codigo": "veracruz"
    },
    {
        "nombre_sucursal": "Sucursal Villahermosa",
        "calle": "Ave. Antimonio",
        "num_ext": "S/N",
        "num_int": "LOCAL 4",
        "codigo_postal": "86010",
        "colonia": "Ciudad Industrial",
        "estado": "Tabasco",
        "ciudad": "Villahermosa",
        "pais": "México",
        "telefono": "(993)140-7424",
        "codigo": "villahermosa"
    }
]